name: 'Construct Resources AWS'

on:
  push:
    branches: [main]

jobs:
  pack_deploy:
    name: Build and deploy Resources
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION_NAME }}        
        
    - name: Creating The Requirements Stack
      run: |       
        aws cloudformation create-stack \
        --stack-name dataengineer-requirements \
        --template-body file://cloudformation/requirements.yaml

    - name: Build the ECR Image for Lambda Extract
      run: |
        sh lambda_extract/dockerbuild.sh

    - name: Uploading the Glue Spark Jobs
      run: |
        sh gluejobs/upload_gluejobs.sh

    - name: Creating The Requirements Stack
      run: |
        aws cloudformation create-stack \
          --stack-name dataengineer-stack \
          --template-body file://cloudformation/deploy.yaml     