name: 'Destruct Resources AWS'

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Destroying all AWS Resources created by Cloudformation."
        required: false
        default: "destroy"

jobs:
  pack_deploy:
    name: Destroy AWS Resources
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION_NAME }}        
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Deleting s3 files
      run: |

        pip3 install boto3
        python3 lambda_delete/delete_objects.py

    - name: Deleting The Requirements Stack
      run: |       
        aws cloudformation delete-stack \
            --stack-name dataengineer-requirements

    - name: Deleting The Data Engineer Stack
      run: |       
        aws cloudformation delete-stack \
            --stack-name dataengineer-stack